# Beta automation harness leveraging AL Layer Manager bridge + upstream layer_manager

blueprints:
  automation:
    home_adaptive_lighting:al_layer_manager_sonos_wake:
      name: "AL Layer Manager - Sonos Wake"
      description: "Coordinated wake routine using al_layer_manager services with upstream layer_manager execution"
      domain: automation
      input:
        zone:
          name: Zone ID
          selector:
            text:
        alarm_time:
          name: Alarm Time Input Datetime
          selector:
            entity:
              domain: input_datetime
        sonos_player:
          name: Sonos Player
          selector:
            entity:
              domain: media_player
        bridge_helper:
          name: Bridge Helper Sensor
          selector:
            entity:
              domain: sensor
  script:
    home_adaptive_lighting:al_layer_manager_manual_scene:
      name: "AL Layer Manager - Manual Scene"
      description: "Activate a manual scene via layer_manager.insert_state"
      domain: script
      blueprint:
        input:
          zone:
            selector:
              text:
          brightness:
            selector:
              number:
                min: 0.1
                max: 1.0
                step: 0.05
          kelvin:
            selector:
              number:
                min: 2200
                max: 6000
                step: 100

automation:
  - alias: "ALM Wake Routine"
    use_blueprint:
      path: home_adaptive_lighting:al_layer_manager_sonos_wake
      input:
        zone: office
        alarm_time: input_datetime.office_alarm
        sonos_player: media_player.office
        bridge_helper: sensor.al_layer_manager_office_state
  - alias: "ALM Evening Relax"
    trigger:
      - platform: time
        at: "19:00:00"
    condition:
      - condition: state
        entity_id: binary_sensor.household_present
        state: "on"
    action:
      - service: al_layer_manager.set_mode
        data:
          zone_id: office
          mode: relax
          brightness_multiplier: 0.7
          kelvin_adjustment: -600
      - service: al_layer_manager.sync_zone
        data:
          zone_id: office
      - delay: "00:30:00"
      - service: al_layer_manager.clear_mode
        data:
          zone_id: office
          mode: relax

script:
  al_layer_manager_manual_scene:
    description: "Manual scene helper that mirrors bridge output"
    fields:
      zone_id:
        example: office
      brightness:
        example: 0.65
      kelvin:
        example: 3400
    sequence:
      - service: al_layer_manager.start_manual_override
        data:
          zone_id: "{{ zone_id }}"
          brightness: "{{ brightness }}"
          kelvin: "{{ kelvin }}"
          reason: blueprint_manual
          duration: 45
      - service: al_layer_manager.sync_zone
        data:
          zone_id: "{{ zone_id }}"
