# Service definitions for Adaptive Lighting Pro

adjust_brightness:
  name: Adjust Brightness
  description: Adjust global brightness using asymmetric boundary logic. Positive values raise minimum, negative lower maximum.
  fields:
    value:
      name: Brightness Adjustment
      description: Brightness adjustment in percent (-100 to +100)
      required: true
      example: 25
      selector:
        number:
          min: -100
          max: 100
          step: 5
          unit_of_measurement: "%"
    temporary:
      name: Temporary Adjustment
      description: If true, starts smart timeout (expires after context-aware duration). If false, adjustment persists indefinitely.
      required: false
      default: true
      example: false
      selector:
        boolean:

adjust_color_temp:
  name: Adjust Color Temperature
  description: Adjust global color temperature using asymmetric boundary logic. Positive = cooler (higher K), negative = warmer (lower K).
  fields:
    value:
      name: Color Temperature Adjustment
      description: Color temperature adjustment in Kelvin (-2500 to +2500)
      required: true
      example: -500
      selector:
        number:
          min: -2500
          max: 2500
          step: 100
          unit_of_measurement: "K"
    temporary:
      name: Temporary Adjustment
      description: If true, starts smart timeout (expires after context-aware duration). If false, adjustment persists indefinitely.
      required: false
      default: true
      example: false
      selector:
        boolean:

apply_scene:
  name: Apply Lighting Scene
  description: Apply a predefined lighting scene. ALL_LIGHTS scene clears all offsets and returns to pure adaptive lighting.
  fields:
    scene:
      name: Scene
      description: The scene to apply
      required: true
      example: "evening_comfort"
      selector:
        select:
          options:
            - label: "All Lights (Clear to Adaptive)"
              value: "all_lights"
            - label: "No Spotlights"
              value: "no_spotlights"
            - label: "Evening Comfort"
              value: "evening_comfort"
            - label: "Ultra Dim"
              value: "ultra_dim"

cycle_scene:
  name: Cycle Scene
  description: Cycle to the next scene in the sequence. Useful for physical button control.

reset_manual_adjustments:
  name: Reset Manual Adjustments
  description: Reset manual brightness and warmth adjustments AND scene offsets to zero. Does not cancel manual control timers.

reset_all:
  name: Nuclear Reset
  description: Completely reset all settings - adjustments, scene offsets, and timers. Restores full adaptive lighting control.

clear_manual_control:
  name: Clear Manual Control
  description: Clear manual control timer for a specific zone or all zones to restore adaptive lighting.
  fields:
    zone_id:
      name: Zone ID
      description: Zone to clear manual control for (optional, clears all if not specified)
      required: false
      example: "bedroom"
      selector:
        text:

set_wake_alarm:
  name: Set Wake Alarm
  description: Manually set wake alarm time to trigger wake sequence (for testing or non-Sonos alarms).
  fields:
    alarm_time:
      name: Alarm Time
      description: Time when alarm will fire (wake sequence starts 15 minutes before)
      required: true
      example: "2025-10-02T06:30:00-07:00"
      selector:
        datetime:

clear_wake_alarm:
  name: Clear Wake Alarm
  description: Clear wake alarm and cancel active wake sequence.
