name: Lint

on:
  push:
    branches: [main, develop]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - uses: snok/install-poetry@v1
      - run: poetry install --with dev
      - run: poetry run ruff check .
      - run: poetry run black --check .
      - run: poetry run isort --check-only .
