name: Tests

on:
  push:
    branches: [main, develop]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - uses: snok/install-poetry@v1
      - run: poetry install --with dev
      - run: poetry run python scripts/prepare_fixtures.py
      - run: poetry run pytest --maxfail=1 --disable-warnings
